parameters:
- name: agents
  type: object
- name: configs
  type: object

stages:
- ${{ each agent in parameters.agents }}:
  - ${{ if not(agent.skip) }}:
    - ${{ each config in parameters.configs }}:
      - ${{ if not(config.skip) }}:
        - stage: ${{ replace(agent.os, '-', '_') }}_${{ config.queue }}_${{ replace(config.scu, '.', '_') }}
          dependsOn: []
          pool:
            name: smoketests-middleware
            demands:
              - SmokeTests
              - SmokeTests.Queue.${{ config.queue }}
              - SmokeTests.SCU.${{ config.scu }}
              - SmokeTests.OS -equals ${{ agent.os }}
          jobs:
          - job:
            displayName: Smoke Tests
            workspace:
              clean: all
            steps:

            - checkout: none

            - pwsh: New-Item -ItemType directory -Path "$(Build.SourcesDirectory)/logs"
              displayName: Setup Directories

            - template: test.yaml
              parameters:
                queue: ${{ config.queue }}
                scu: ${{ config.scu }}
                cashbox: ${{ config.cashbox }}
                init: ${{ config.init }}
                pre: ${{ config.pre }}
                post: ${{ config.post }}
                mono: ${{ eq(agent.mono, True) }}

            - publish: logs
              artifact: logs-${{ agent.os }}-${{ config.queue }}-${{ replace(config.scu, '.', '-') }}
              condition: succeededOrFailed()
            
            - task: PublishTestResults@2
              condition: succeededOrFailed()
              inputs:
                testResultsFormat: JUnit
                testResultsFiles: $(Build.SourcesDirectory)/newman.xml
                testRunTitle: ${{ agent.os }}-${{ config.queue }}-${{ replace(config.scu, '.', '-') }}
                buildPlatform: ${{ agent.os }}
                buildConfiguration: ${{ config.queue }}-${{ replace(config.scu, '.', '-') }}
              
